schema: src/main/resources/graphql/schema.graphqls
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: http://localhost:8085/graphql
      headers:
        user-agent: JS GraphQL
      introspect: false
